# Configuration file for i18n-check validation.
# See https://github.com/activist-org/i18n-check for details.

src-dir: i18n
i18n-dir: i18n/locales
i18n-src: i18n/locales/en-US.json

file-types-to-check: []  # not needed

checks:
  key-formatting:
    active: true
  non-source-keys:
    active: true
  repeat-keys:
    active: true
  repeat-values:
    active: true
  sorted-keys:
    active: true
  nested-files:
    active: true
  aria-labels:
    active: true
  alt-texts:
    active: true
